### ISSUE TITLE
Load equirectangular texture?

### ISSUE THREAD

**Issue by danielCrespo01** [joekim/MobileMeetup#2]
It is possible to load a equirectangular and not see the vertices black of the sphere?

**Comment by sweetmandm** [comment]
@danielCrespo01 this is an old collection of simple demonstrations and probably isn't the best place to address your question, you might have more luck asking over at http://stackoverflow.com if you provide a more detailed explanation of what you're trying to achieve.

**Comment by danielCrespo01** [comment]
Thank you @sweetmandm .
